kind: pipeline
type: docker
name: auto-and-manual-steps

steps:
  # 第1个step - 自动触发
  - name: auto-step
    image: alpine
    commands:
      - echo "=== 自动触发步骤 ==="
      - echo "项目名称: ${DRONE_REPO}"
      - echo "当前分支: ${DRONE_COMMIT_BRANCH}"

