kind: pipeline
type: docker
name: auto-and-manual-steps

steps:
  - name: auto-step
    image: alpine
    commands:
      - echo "=== 自动触发步骤 ==="

  - name: manual-step-1
    image: alpine
    commands:
      - echo "=== 第一个手动步骤 ==="
    when:
      event: [ manual ]
    depends_on: [ auto-step ]

  - name: manual-step-2
    image: alpine
    commands:
      - echo "=== 第二个手动步骤 ==="
    when:
      event: [ manual ]
    depends_on: [ manual-step-1 ]
