kind: pipeline
type: docker
name: manual-trigger-demo

steps:
  # 第一个step - 自动触发
  - name: auto-step
    image: alpine
    commands:
      - echo "This step runs automatically on commit"
      - echo "项目名称: 123123"
      - echo "当前分支: 123123"
      - echo "提交SHA: 123123"
      - echo "提交信息: 123123"

  # 第二个step - 手动触发
  - name: manual-step-1
    image: alpine
    commands:
      - echo "===== 这是第一个手动步骤 ====="
      - echo "项目: 123123"
      - echo "构建编号: 123123"
      - echo "触发事件: 123123"
    when:
      event: manual
    depends_on: [ auto-step ]

  # 第三个step - 手动触发
  - name: manual-step-2
    image: alpine
    commands:
      - echo "===== 这是第二个手动步骤 ====="
      - echo "构建状态: 123123"
      - echo "提交作者: 123123"
      - echo "提交时间: 123123"
    when:
      event: manual
    depends_on: [ manual-step-1 ]
