kind: pipeline
type: docker
name: auto-and-promote-steps

steps:
  - name: auto-step
    image: alpine
    commands:
      - echo "=== 自动触发步骤 ==="

---
kind: pipeline
type: docker
name: auto-and-promote-steps
steps:
  - name: promote-step-1
    image: alpine
    commands:
      - echo "=== 第一个手动步骤 ==="
    settings:
      approve: true
      message: "请确认是否继续部署？"
    depends_on: [ auto-step ]


---
kind: pipeline
type: docker
name: auto-and-promote-steps
steps:
  - name: promote-step-2
    image: alpine
    commands:
      - echo "=== 第二个手动步骤 ==="
    depends_on: [ promote-step-1 ]

---
kind: pipeline
type: docker
name: auto-and-promote-steps
steps:
  - name: promote-step-3
    image: alpine
    commands:
      - echo "=== 第三个手动步骤 ==="
    when:
      event: [ promote ]
    depends_on: [ promote-step-2 ]
