kind: pipeline
type: docker
name: auto-and-manual-steps

steps:
  # 第1个step - 自动触发
  - name: auto-step
    image: alpine
    commands:
      - echo "=== 自动触发步骤 ==="
      - echo "项目名称: ${DRONE_REPO}"
      - echo "当前分支: ${DRONE_COMMIT_BRANCH}"

  # 第2个step - 手动触发
  - name: manual-step-1
    image: alpine
    commands:
      - echo "=== 第一个手动步骤 ==="
      - echo "这是需要手动触发的第一步"
    when:
      event: [ manual ]
    depends_on: [ auto-step ]

  # 第3个step - 手动触发
  - name: manual-step-2
    image: alpine
    commands:
      - echo "=== 第二个手动步骤 ==="
      - echo "这是需要手动触发的第二步"
    when:
      event: [ manual ]
    depends_on: [ manual-step-1 ]
