---
- hosts: all
  tasks:
    - name: 获取精简OS信息
      ansible.builtin.command: |
        echo "主机名: $(hostname)"
        echo "内核: $(uname -sr)"
        { [ -f /etc/os-release ] && . /etc/os-release && echo "系统: $PRETTY_NAME" || echo "系统: $(cat /etc/*release 2>/dev/null | head -n1)"; }
      register: os_info
      changed_when: false

    - name: 显示信息
      ansible.builtin.debug:
        msg: "{{ os_info.stdout }}"
